name: Build Xamarin.Android app

on: [push]

jobs:
  build:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: nuget restore 'DdfGuide.sln'

    - name: Build
      run: msbuild '/DdfGuide.Android/DdfGuide.Android.csproj' /t:PackageForAndroid /p:Configuration=Debug
